spellchecker: aspell

documents:
- name: MkDocs
  language: html
  src:
  - site
  excludes:
  html_options:
    attributes:
    - title
    - alt
    ignores:
    - code
    - pre
    - a.magiclink-compare
    - a.magiclink-commit
    - span.keys
    - .MathJax_Preview
    - .md-nav__link
    - .md-footer-custom-text
    - .md-source__repository

- name: Python Source
  language: python
  src:
  - pymdownx
  - tests
  - tools
  exclude:
  - tools/tags
  html_options:
    attributes:
    - title
    - alt
    ignores:
    - code
    - pre
    - a.magiclink-compare
    - a.magiclink-commit
  language_options:
    markdown_extensions:
      markdown.extensions.smarty:
        smart_quotes: false
      pymdownx.betterem:
      markdown.extensions.def_list:
      markdown.extensions.tables:
      pymdownx.superfences:
      pymdownx.highlight:
        css_class: codehilite
        extend_pygments_lang:
          - name: php-inline
            lang: php
            options:
              startinline: true
          - name: pycon3
            lang: pycon
            options:
              python3: true
      pymdownx.inlinehilite:
      pymdownx.magiclink:
        repo_url_shortener: true
        repo_url_shorthand: true
        social_url_shorthand: true
        user: facelessuser
        repo: pymdown-extensions
      pymdownx.tilde:
      pymdownx.caret:
      pymdownx.smartsymbols:
      pymdownx.escapeall:
        hardbreak: True
        nbsp: True
      pymdownx.tasklist:
        custom_checkbox: true
  dictionary:
  - Dedent
  - UrlParse
  - octocat
  - ord
  - netpath

# Global dictionary
dictionary:
- API
- Arithmatex
- AttrList
- BeautifulSoup
- BetterEm
- Bitbucket
- CDN
- CDNs
- CSS
- Changelog
- Cloudflare
- CodeHilite
- CodeHilite's
- CriticMarkup
- Ctrl
- Dicts
- Emoji
- EmojiOne
- EmojiOne's
- Esc
- EscapeAll
- ExtraRawHTML
- GFM
- GIF
- Gemoji
- Gemoji's
- GitHub
- GitHub's
- GitHubEmoji
- GitLab
- GitLab's
- HeaderAnchor
- HeaderAnchor's
- Inline
- InlineHilite
- InlineHilite's
- JPEG
- JSON
- JavaScript
- KBD
- LaTeX
- Limberg
- MERCHANTABILITY
- MagicLink
- MathJax
- MkDocs
- Mkdoc's
- NONINFRINGEMENT
- Num
- OAuth
- Octicons
- PHP
- PNG
- PNGs
- Pandoc
- PathConverter
- PlainHTML
- ProgressBar
- PyMdown
- PyYaml
- PyYaml's
- Pygments
- Pymdownx
- Reindent
- SCSS
- SVG
- SVGs
- Slugify
- SmartSymbols
- StripHTML
- Stylesheets
- SuperFences
- Tasklist
- Toc
- Tox
- Twemoji
- Twitter's
- UML
- UTF
- Unescape
- Virtualenv
- Waylan
- YAML
- backrefs
- backtick
- backticks
- blockquote
- blockquotes
- bool
- builtins
- checkboxes
- cmd
- config
- coveragepy
- customizable
- dev
- dict
- dicts
- docstrings
- ebeweber
- emoji
- emojione
- escaper
- facelessuser
- formatter
- gemoji
- gfm
- gforcada
- github
- highlighter's
- html
- inline
- ish
- jQuery
- js
- kbd
- linkafies
- linter
- lowercased
- lowercases
- md
- mkdocs
- mrab
- mrabarnett
- namespace
- nd
- ned
- nl
- online
- plugin
- plugins
- plusminus
- polyfill
- polyfilled
- polyfills
- pre
- prepend
- prepended
- prepending
- prepends
- preprocessor
- px
- py
- pycqa
- pymdown
- pymdownx
- pypi
- pytest
- raphael
- regex
- reindent
- reinstalling
- repo
- requesters
- revisioned
- sanitizer
- shortener
- shortname
- shortnames
- slugify
- squidfunk
- stylesheet
- stylesheets
- sortable
- sublicense
- superfences
- syntaxes
- th
- thumbsup
- tox
- uc
- un
- underscore's
- unicode
- uslugify
- versa
- whitespace
